# Generated by Django 4.1.2 on 2022-10-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0002_cart_cart_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cart_item',
            name='total_item',
            field=models.IntegerField(default=0),
        ),
    ]
