# Generated by Django 4.1.2 on 2022-10-23 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0005_order_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
