# Generated by Django 4.1.2 on 2022-10-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0008_order_paid_order_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_discription',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
