# Generated by Django 4.1.2 on 2022-10-23 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0009_order_order_discription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_discription',
            new_name='order_description',
        ),
    ]
