# Generated by Django 4.1.2 on 2022-10-24 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0010_rename_order_discription_order_order_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
