# Generated by Django 4.1.2 on 2022-10-24 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0011_alter_order_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='apartment',
            new_name='payment',
        ),
    ]
