# Generated by Django 4.1.2 on 2022-10-24 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0013_alter_order_post_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
    ]
