# Generated by Django 4.1.2 on 2022-10-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0015_alter_order_post_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='post_code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
