# Generated by Django 4.1.2 on 2022-10-25 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0016_alter_order_post_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='post_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
