# Generated by Django 4.1.2 on 2022-10-25 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0020_alter_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
    ]
