# Generated by Django 4.1.2 on 2022-10-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0024_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order_items',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
