# Generated by Django 4.1.2 on 2022-10-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0025_remove_order_status_order_items_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
        migrations.AddField(
            model_name='order_items',
            name='paid',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
