# Generated by Django 4.1.2 on 2022-10-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0026_remove_order_paid_order_items_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='post_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
