# Generated by Django 4.1.2 on 2022-10-26 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category2_product_product_category2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_category2',
        ),
        migrations.AddField(
            model_name='product',
            name='product_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products2', to='products.category2'),
        ),
    ]
