# Generated by Django 4.1.2 on 2022-10-26 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_product_category2_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category2',
            new_name='Discount_cat',
        ),
    ]
