# Generated by Django 4.1.2 on 2022-10-26 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_category2_discount_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='percentage_offer',
        ),
    ]
