# Generated by Django 4.1.2 on 2022-10-27 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_product_status_product_discount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Discount_cat',
            new_name='New_cat',
        ),
        migrations.AddField(
            model_name='product',
            name='New_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.new_cat'),
        ),
    ]
