# Generated by Django 4.1.2 on 2022-10-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_discount_cat_new_cat_product_new_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='New_category',
        ),
        migrations.AddField(
            model_name='product',
            name='new',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='percentage',
            field=models.CharField(blank=True, choices=[('10%', '10%'), ('20%', '20%'), ('30%', '30%'), ('40%', '40%'), ('50%', '50%'), ('60%', '60%'), ('70%', '70%'), ('80%', '80%'), ('90%', '90%'), ('99%', '99%')], default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.DeleteModel(
            name='New_cat',
        ),
    ]
