# Generated by Django 4.1.2 on 2022-10-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_product_new_category_product_new_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Makeup_Set',
        ),
        migrations.AddField(
            model_name='product',
            name='Full_makeup_set',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
