# Generated by Django 4.1.2 on 2022-10-29 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_delete_makeup_set_product_full_makeup_set'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=100, null=True)),
                ('discription', models.TextField(blank=True, max_length=100, null=True)),
                ('slider_image', models.ImageField(upload_to='upload/slider')),
            ],
        ),
    ]
