# Generated by Django 4.1.2 on 2022-10-29 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_slider_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact', models.IntegerField(blank=True, max_length=11, null=True)),
                ('address', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
